### ISSUE TITLE
R1.8

### ISSUE THREAD

**Issue by Kouvan** [SachsenCoder/Anita#19] opened 2016-11-09 08:42 UTC
Hi Christian. Thank you very much for the new release. I still experience the error mentioned by Thymopat: "After clicking on "Fetch Data" it will crash on Windows 10".

**Comment by hirenshah** [comment] 2017-01-28 08:45
Yep, same issue here... cannot seem to make it work on Windows 10 :(

**Comment by ChristianG1984** [comment] 2017-02-04 16:50
Ok, I figured out the problem and it is fixed now. :-)
(By the way: The wikifeet website becomes more and more ugly, because of the crappy and aggressive ads around.)

**Closed as completed by ChristianG1984** 2017-02-04 16:50 UTC
Labels: critical error

**Comment by hirenshah** [comment] 2017-02-04 17:49
Confirmed.  Works fine now.  Thanks :)
